---
# This is kustomization file for ${{ values.name }} application
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - base/deployment.yaml
  - base/service.yaml
namespace: ${{ values.namespace }}
commonLabels:
  author: ${{values.owner}}
