apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{values.name}}
  namespace: argocd
spec:
  project: default # Segregated by BU - e.g 'PCI' for pci applications and 'Crypto' for crypto application.   
  source:
    repoURL: https://github.com/moquintanilha/${{values.name}}.git
    targetRevision: master # Branch of the implement, e.g 'staging' or 'production'. Branch default is 'initial-scaffolding'
    path: ${{values.name}}
  destination:
    namespace: ${{values.namespace}}
    server: "https://kubernetes.default.svc"
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true