apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: devops-tools
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
    kustomize.buildOptions: --load-restrictor LoadRestrictionsNone
    kustomize.buildOptions.v4.4.0: --output /tmp